from .save import Save
from .search import Search
from .calc import Calc
from .weather import Weather
from .name import Name
from .hobby import Hobby
from .is_yes import IsYes
from .save_people import SavePeople
from .recognize_object import RecognizeObject
from .recognize_face import RecognizeFace
from .learn import Learn
from .smart_home import SmartHome